/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Transaction = {
  id?: string;
  /**
   * @format double
   */
  amount?: number;
  description?: string;
  /**
   * @format int32
   * @default 0
   */
  type?: 0 | 1;
  /**
   * @format date-time
   */
  date?: string;
};
